version: '3'
services:
  vault:
    image: "vault:latest"
    cap_add:
        - IPC_LOCK
    volumes:
        - vault-file:/vault/file
        - vault-unseal:/vault/unseal
        - ./config:/vault/config:rw
    command: >
        vault server -config='/vault/config'
    environment:
        - VAULT_ADDR=http://0.0.0.0:8200
        - VAULT_API_ADDR=http://0.0.0.0:8200
        - VAULT_ADDRESS=http://0.0.0.0:8200
    ports:
      - "8200:8200"
volumes:
  vault-file:
    driver: local
  vault-unseal:
    driver: local